version: '3'
services:
    pgsql:
        image: vladimirmihov/postgres
        environment:
            - POSTGRES_PASSWORD=vladovlado
        volumes:
            - vlado-pgdata:/var/lib/postgresql/data
    spring:
        image: vladimirmihov/spring
        environment:
            - HOST_IP=localhost
        ports:
            - 8080:8080
        volumes:
            - vlado-static:/static
        links:
            - pgsql:db
        depends_on:
            - pgsql
    static:
        image: vladimirmihov/static
        ports:
            - 8090:8090
        volumes:
            - vlado-static:/static
    angular:
        image: vladimirmihov/angular-nginx
        ports:
            - 80:8080
        links:
            - spring:backend
        depends_on:
            - pgsql
            - spring
            - static
volumes:
    vlado-pgdata:
    vlado-static:
